/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UID */

#ifndef _Included_UID
#define _Included_UID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UID
 * Method:    setuid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UID_setuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     UID
 * Method:    seteuid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UID_seteuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     UID
 * Method:    getuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UID_getuid
  (JNIEnv *, jclass);

/*
 * Class:     UID
 * Method:    geteuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UID_geteuid
  (JNIEnv *, jclass);

/*
 * Class:     UID
 * Method:    setgid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UID_setgid
  (JNIEnv *, jclass, jint);

/*
 * Class:     UID
 * Method:    setegid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UID_setegid
  (JNIEnv *, jclass, jint);

/*
 * Class:     UID
 * Method:    getgid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UID_getgid
  (JNIEnv *, jclass);

/*
 * Class:     UID
 * Method:    getegid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UID_getegid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
